config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :links
  post '/upvotes/:link_id', to: 'upvotes#create_upvote', as: 'upvote_link'
  resources :upvotes

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :upvotes

  validates :title, presence: true
  

  def scores
    upvotes.count
  end

  def vote
    upvotes.count + 1
  end



end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :link
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links

  validates :name, presence: true
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all.sort_by { |l| [l.scores, l.title] }.reverse!
  end

  def show
   link = Link.find(params[:id])
   if link
      @link = link
    else
      render_not_found
    end
  end

  def create

    Link.create(user_id: params[:link][:user_id],
               title: params[:link][:title],
               body:params[:link][:body])

     redirect_to '/links'
   end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def index
    @upvotes = Upvote.all
  end

  def create_upvote
   @upvote = Upvote.new
   @upvote.link = Link.find(params[:link_id])
   @upvote.save
   redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<h1> Reddit Homepage </h1>

<a href="/links/new">Make a new post!</a>

<div>
  <ol>
  <% @links.each do |link| %>
    <li><a href="<%= link.title %>"><%= link.title %></a>
    <p>Posted by: <%= link.user.username unless link.user.blank? %> </p>
    <p>Number of Upvotes: <%= link.scores %></p>
    <%= button_to 'Upvote', upvote_link_path(link.id),  method: :post %>
    <% end %>
  </ol>
</div>

app/views/links/new.html.erb
<h2>Create a new link!</h2>
<div>
<%= render partial: 'shared/form' %>
</div>

app/views/links/show.html.erb
S

app/views/shared/_form.html.erb
<div class='row'>
  <div class='twelve columns'>

    <% if @link && @link.errors %>
     <% @link.errors.full_messages.each do |msg| %>
       <p class='form-error'> <%= msg %> </p>
     <% end %>
   <% end %>

    <%= form_for Link.new do |l| %>
      <div class='row'>
        <div class='three columns'>
          <%= l.label :title %>
          <%= l.text_field :title, class: 'input-field title', placeholder: "www.google.com" %>
        </div>

        <div class='three columns'>
          <%= l.label :body %>
          <%= l.text_field :body, class: 'input-field body', placeholder: "Add a description here..." %>
        </div>

        <div class='three columns'>
          <%= l.label :user_id %>
          <%= l.select :user_id, options_for_select(User.all.map { |user| [user.username, user.id] }), class: 'input-field user_id', placeholder: "Type here..." %>
        </div>
      </div>
      <div class='row'>
        <%= l.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/upvotes/index.html.erb
<h1> All Upvotes </h1>


<div>
  <ol>
  <% @upvotes.each do |upvote| %>
    <li><p><%= upvote.link.title %> </p>
  <% end %>
  </ol>
</div>

app/views/users/index.html.erb
<h1> All Users </h1>


<div>
  <ol>
  <% @users.each do |user| %>
    <li><p>Name: <%= user.name %> </p>
    <p>Reddit Handle: <%= user.username %> </p></li>
  <% end %>
  </ol>
</div>